from selenium import webdriver
from selenium.webdriver.common.by import By
import time
options = webdriver.ChromeOptions()
options.add_experimental_option('detach',True)
driver = webdriver.Chrome(options=options)
driver.get('https://www.robotevents.com/robot-competitions/vex-robotics-competition')
# element = driver.find_element('name','city')
# element.send_keys('sammamish')
# element = driver.find_element(By.NAME,"city")
# element.send_keys('parth')
# element = driver.find_element(By.ID,"city")
# element.send_keys('parths id')
# element = driver.find_element(By.CLASS_NAME,"form-control")
# element.send_keys('parths fc')

element = driver.find_element(By.ID,"competitions-app")
element2 = element.find_element(By.TAG_NAME, "p")
element3 = element2.find_element(By.TAG_NAME,"strong")
print(element3.text)
element4 = element.find_element(By.CLASS_NAME, "col-sm-6")
element5 = element4.find_element(By.TAG_NAME, "p")
element6 = element5.find_element(By.TAG_NAME,"strong")
print(element6.text)
element5 = element4.find_element(By.TAG_NAME, "p1")
element6 = element5.find_element(By.TAG_NAME,"strong")
print(element6.text)
element7 = element4.find_element(By.XPATH, "//div[@class='col-sm-6']/p[1]")
print(element7.text)
element8 = element4.find_element(By.XPATH, "//div[@class='col-sm-6']/p[2]")
print(element8.text)
element9 = element4.find_element(By.XPATH, "//div[@class='col-sm-6']/p[3]")
print(element9.text)
element10 = element4.find_element(By.XPATH, "//div[@class='col-sm-6']/p[4]")
print(element10.text)