from selenium import webdriver
import time
options = webdriver.ChromeOptions()
options.add_experimental_option('detach',True)
driver = webdriver.Chrome(options=options)
driver.get('https://www.robotevents.com/robot-competitions/vex-robotics-competition')
print(driver.current_url)
print(driver.title)
driver.get('https:///www.google.com')
time.sleep(2)
driver.back()
time.sleep(2)
driver.forward()
driver.refresh()
driver.maximize_window()
time.sleep(1)
driver.minimize_window()
driver.close()
driver.quit()